# Create a workflow that triggers manually and:
# 1. Print our slogan
# 2. Guess our magic number

name: Magic Number Workflow

on:
  workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  print_and_guess:
    runs-on: ubuntu-latest
    steps:
      - name: Print our slogan
        run: |
          echo "Our slogan is: ${{ vars.SLOGAN }}"  # Accesses the repository variable 'SLOGAN'

      - name: Print our secret number
        run: |
          echo "Magic Number (encoded): $(echo -n "${{ secrets.MAGIC_NUMBER }}" | base64)"
